---
title: "Simulação - Aula 4"
author: "Panosso, AR"
date: "2026-03-19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warning = FALSE,
                      error = FALSE,
                      message = FALSE)
```


Carregando Pacotes
```{r}
library(tidyverse)
```

Simulando uma população
```{r}
set.seed(1235)
population <- rnorm(100000, mean = 50, sd=3)

population |> 
  as_tibble() |> 
  ggplot(aes(x=value)) +
  geom_histogram(color="black", fill="lightblue") +
  theme_bw()
```

```{r}
mean(population)
var(population)
sd(population)
```

Amostragem

```{r}
medias <- vector()
s_n <- s_n_1 <- vector()
for(i in 1:100){
  my_sample <- sample(population, 10, replace = TRUE)
  medias[i] <- mean(my_sample)
  s_n[i] <- (sum(my_sample^2) - (sum(my_sample))^2/length(my_sample))/length(my_sample)
  s_n_1[i] <- (sum(my_sample^2) - (sum(my_sample))^2/length(my_sample))/(length(my_sample)-1)
}

medias |> 
  as_tibble() |> 
  ggplot(aes(x=value)) +
  geom_histogram(color="black", fill="lightblue") +
  theme_bw()
```


```{r}
mean(s_n)
var(population)
mean(s_n_1)

tibble(
  medias,
  s_n,
  s_n_1
) |> 
  ggplot(aes(x=medias, y=s_n)) +
  geom_point() +
  geom_vline(xintercept = mean(population)) +
  geom_hline(yintercept = var(population)) +
  xlim(40,60)+
  ylim(0,50)

```

```{r}
tibble(
  medias,
  s_n,
  s_n_1
) |> 
  ggplot(aes(x=medias, y=s_n_1)) +
  geom_point() +
  geom_vline(xintercept = mean(population)) +
  geom_hline(yintercept = var(population)) +
  xlim(40,60)+
  ylim(0,50)
```

```{r}
library(tidyverse)

dados <- c(23,32,16,19,17,19,32,34,26,28, 
28,21,28,27,24,34,24,20,33,29, 
33,38,32,40,24,27,33,26,45,30,
28,29,34,15,36,20,31,29,29,16, 
34,39,30,20,41,18,24,15,20,32)

dados[order(dados)]


table(dados) |> max()

dados |> 
  tibble::as_tibble() |> 
  summarise(
    Média = mean(value),
    Mediana = median(value),
    `Desvio Padrão` = sd(value),
    CV = 100*`Desvio Padrão`/Média
  ) 

diff(range(dados))

length(dados[dados>= 20])/length(dados)

```
```{r}
# Dados
K <- c(28,32,21,30,19,22,22,28,21,28,42,58,41,19,21,30,23,15,24,18,36,20,32,20,38,27,28,38,29,36)
pH <- c(8.2,8.2,8.3,8,7.8,8,8.3,8.2,7.3,8.4,7.9,7.1,8.3,8.3,7.8,8,7,8,8,6,8,8,8,8,8,8,8,8,8,8.1)
P <- c(27,1.4,2.4,12.1,4.8,5.3,4.8,3,2.9,1,2.9,16.5,1.5,6,2.9,7,2,5,24,1,5,11,11,4,3,3,5,7,3,17)

dados <- list(K=K, pH=pH, P=P)

# Funções auxiliares
cv <- function(x) sd(x)/mean(x)*100

# a) Estatísticas
resumo <- lapply(dados, function(x){
  c(
    media = mean(x),
    mediana = median(x),
    dp = sd(x),
    Q1 = quantile(x, 0.25),
    Q3 = quantile(x, 0.75),
    assimetria = agricolae::skewness(x),
    curtose = agricolae::kurtosis(x),
    CV = cv(x),
    min = min(x),
    max = max(x)
  )
})


tabela <- data.frame(
  Variavel = c("K", "pH", "P"),
  Media = c(28.20, 7.9067, 6.75),
  Mediana = c(28.00, 8.00, 4.80),
  DP = c(9.1967, 0.4835, 6.6024),
  Q1 = c(21.00, 8.00, 2.90),
  Q3 = c(32.00, 8.175, 7.00),
  Assimetria = c(1.249563, -2.605442, 1.853952),
  Curtose = c(2.323401, 8.021439, 3.012404),
  CV = c(32.6124, 6.1148, 97.8132),
  Min = c(15.00, 6.00, 1.00),
  Max = c(58.00, 8.40, 27.00)
)

tabela


data.frame(resumo)

# b) Histogramas + frequência acumulada
par(mfrow=c(3,2))

for(nome in names(dados)){
  x <- dados[[nome]]
  
  # Histogramas com k=5 classes
  h <- hist(x, breaks=5, main=paste("Histograma -", nome),
            xlab=nome, col="gray", border="black")
  
  # Quartis
  Q1 <- quantile(x, 0.25)
  Q2 <- median(x)
  Q3 <- quantile(x, 0.75)
  
  abline(v=Q1, col="blue", lwd=2, lty=2)
  abline(v=Q2, col="red", lwd=2)
  abline(v=Q3, col="blue", lwd=2, lty=2)
  
  # Frequência acumulada (ogiva)
  x_ord <- sort(x)
  n <- length(x)
  FreqAc <- (1:n)/n
  
  plot(x_ord, FreqAc, type="s", main=paste("Freq. Acumulada -", nome),
       xlab=nome, ylab="F(x)")
  
  abline(v=Q1, col="blue", lwd=2, lty=2)
  abline(v=Q2, col="red", lwd=2)
  abline(v=Q3, col="blue", lwd=2, lty=2)
}

```

